# Use H2 in-memory database for Docker testing
spring.datasource.url=jdbc:h2:mem:gymdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop

# Disable Eureka
eureka.client.enabled=false

# Disable ActiveMQ
spring.jms.listener.auto-startup=false