spring.datasource.url=jdbc:postgresql://postgres:5432/gym_system_docker
spring.datasource.username=postgres
spring.datasource.password=Randymiller123

eureka.client.service-url.defaultZone=http://eureka:8761/eureka

spring.activemq.broker-url=tcp://activemq:61616
spring.activemq.user=admin
spring.activemq.password=admin