spring.datasource.url=jdbc:postgresql://localhost:5432/gym_test
spring.datasource.username=postgres
spring.datasource.password=Randymiller123

spring.jpa.hibernate.ddl-auto=update

spring.activemq.broker-url=tcp://localhost:61618
spring.activemq.user=admin
spring.activemq.password=admin

eureka.client.enabled=false
spring.cloud.discovery.enabled=false