spring.application.name=gym-crm-system
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_system_spring_boot
spring.datasource.username=postgres
spring.datasource.password=Randymiller123
storage.data.path=classpath:data.json
spring.jpa.hibernate.ddl-auto=create-drop
spring.mvc.servlet.path=/
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
spring.profiles.active=dev
logging.level.com.gym.system=INFO
logging.level.org.springframework.security=INFO
jwt.secret=${JWT_SECRET:my-super-secret-key-my-super-secret-key}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

app.jms.concurrency=3-10
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin